apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: apps/latest
kind: Deployment
metadata:
  name: productpage-latest
  labels:
    app: productpage
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: latest
  template:
    metadata:
      labels:
        app: productpage
        version: latest
    spec:
      containers:
      - name: 21/productpage
        image: fernandocastell/productpage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---