apiVersion: apps/v1
kind: Deployment
type: LoadBalancer
metadata:
  name: ratings-deployment
spec:
  replicas: 2 # enunciado
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings-container
        image: fernandocastell/ratings:1.0
        ports:
        - containerPort: 9080
