apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-deployment
spec:
  replicas: 1  # Ajusta según tus necesidades
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage-container
        image: fernandocastell/reviews:v2
        ports:
        - container