version: '3'
services:
  productpage:
    build: 
      context: ./ProductPage
      dockerfile: Dockerfile
    # ...
    image: 21/productpage
    container_name: 21-productpage
    volumes:
      - ./productpage:/app
    # ...
    ports:
      - "9080:9080"
    environment:
      - SERVICE_VERSION=v1

  # details:
  #   build: ./path_to_details
  #   ports:
  #     - "9080:9080"
  #   environment:
  #     - SERVICE_VERSION=v1
  #     - ENABLE_EXTERNAL_BOOK_SERVICE=true

  # reviews:
  #   build: ./path_to_reviews
  #   ports:
  #     - "9080:9080"
  #   environment:
  #     - SERVICE_VERSION=v1

  # ratings:
  #   build: ./path_to_ratings
  #   ports:
  #     - "9080:9080"
  #   environment:
  #     - SERVICE_VERSION=v1