version: '3'
services:
  productpage:
    build: 
      context: ./ProductPage/
      dockerfile: Dockerfile
    image: 21/productpage #<numero_de_grupo>/<nombre_de_microservicio>
    container_name: 21-productpage
    ports:
      - "9080:9080"
    # environment:
    #   - SERVICE_VERSION=v1
  details:
    build:
      context: ./Details/
      dockerfile: Dockerfile
    image: 21/details #<numero_de_grupo>/<nombre_de_microservicio>
    container_name: 21-details
    ports:
      - "9081:9080"
    # environment:
    #   - SERVICE_VERSION=v1
    #   - ENABLE_EXTERNAL_BOOK_SERVICE=true

  # reviews:
  #   build: ./Reviews
  #   ports:
  #     - "9080:9080"
  #   environment:
  #     - SERVICE_VERSION=v1
  # pc2-2023\DockerCompose\Reviews\reviews-wlpcfg\servers\LibertyProjectServer
  reviews:
    build:
      context: ./Reviews/reviews-wlpcfg/
      dockerfile: Dockerfile
    image: 21/reviews:v3 # v2, v3
    container_name: reviews-container
    ports:
      - "9082:9080"
    environment:
      - ENABLE_RATINGS=true # Variable de entorno
      - SERVICE_VERSION=v3 #v1, v2, v3
      - STAR_COLOR=red #red para la versión3

      # volumes:
      #   - ./src/reviews/reviews-wlpcfg:/app/config


  ratings:
    build: ./Ratings
    image: 21/ratings
    ports:
      - "9083:9080"
    environment:
      - ENABLE_RATINGS=true